version: "3.8"
services:
  app:
    container_name: blog-qalqul-local
    image: blog-qalqul-local
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=develop
      - DB_TYPE=mongo
      - DB_HOST=local
      - DB_PORT=5432
      - DB_USERNAME=localhost
      - DB_PASSWORD=123456
      - DB_NAME=nestjs_dev
      - REDIS_HOST= #
      - REDIS_PORT= #
      - REDIS_DB= #
      - REDIS_PASSWORD= #
      - RABBITMQ_URL= #
      - SECRET_KEY=hhggh5e45454gfgfcfcgfvhv434345678u
